{
    'name' : 'Company',
    'version': '1.0',
    'summary':'Company Employees',
    'sequence':10,
    'description' : """zura managments system software""",
    'category' : "Productivity",
    'license' : 'LGPL-3',
    'data' : [
        'security/ir.model.access.csv',
        'wizards/wizard_report.xml',
        'views/departament_report.xml',
        'views/employeer.xml',
        'views/job_feature.xml',
        'views/job_departament.xml',
        'views/teenager_employeers.xml',        
        'report/report_employeer_details.xml',
        'report/report.xml',              
    ],
    'depends' : [
        'mail',
        'report_xlsx',
    ],
    'demo':[],
    'qweb' :[],
    'installabe' :True,
    'application' :True,
    'auto-instal' :False,
}